apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: default
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostNetwork: true        # uses the node's network directly
      hostPID: true            # access host process info
      tolerations:
        - operator: Exists     # runs on ALL nodes including control-plane
      containers:
        - name: node-exporter
          image: prom/node-exporter:latest
          args:
            - '--path.rootfs=/host'
          ports:
            - containerPort: 9100
              hostPort: 9100
          volumeMounts:
            - name: root
              mountPath: /host
              readOnly: true
      volumes:
        - name: root
          hostPath:
            path: /
