global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ec2-node'
    static_configs:
      - targets: ['ec2-3-84-41-168.compute-1.amazonaws.com']   # ← replace with your EC2 Public IP
        labels:
          instance: 'my-ec2'
          env: 'lab'